package gaml.additions;
import msi.gaml.extensions.multi_criteria.*;
import msi.gama.outputs.layers.charts.*;
import msi.gama.outputs.layers.*;
import msi.gama.outputs.*;
import msi.gama.kernel.batch.*;
import msi.gama.kernel.root.*;
import msi.gaml.architecture.weighted_tasks.*;
import msi.gaml.architecture.user.*;
import msi.gaml.architecture.reflex.*;
import msi.gaml.architecture.finite_state_machine.*;
import msi.gaml.species.*;
import msi.gama.metamodel.shape.*;
import msi.gaml.expressions.*;
import msi.gama.metamodel.topology.*;
import msi.gaml.statements.test.*;
import msi.gama.metamodel.population.*;
import msi.gama.kernel.simulation.*;
import msi.gama.kernel.model.*;
import java.util.*;
import msi.gaml.statements.draw.*;
import  msi.gama.metamodel.shape.*;
import msi.gama.common.interfaces.*;
import msi.gama.runtime.*;
import java.lang.*;
import msi.gama.metamodel.agent.*;
import msi.gaml.types.*;
import msi.gaml.compilation.*;
import msi.gaml.factories.*;
import msi.gaml.descriptions.*;
import msi.gama.util.tree.*;
import msi.gama.util.file.*;
import msi.gama.util.matrix.*;
import msi.gama.util.graph.*;
import msi.gama.util.path.*;
import msi.gama.util.*;
import msi.gama.runtime.exceptions.*;
import msi.gaml.factories.*;
import msi.gaml.statements.*;
import msi.gaml.skills.*;
import msi.gaml.variables.*;
import msi.gama.kernel.experiment.*;
import msi.gaml.operators.*;
import msi.gaml.extensions.genstar.*;
import msi.gama.common.interfaces.*;
import msi.gama.extensions.messaging.*;
import msi.gama.metamodel.population.*;
import msi.gaml.operators.Random;
import msi.gaml.operators.Maths;
import msi.gaml.operators.Points;
import msi.gaml.operators.Spatial.Properties;
import msi.gaml.operators.System;
import static msi.gaml.operators.Cast.*;
import static msi.gaml.operators.Spatial.*;
import static msi.gama.common.interfaces.IKeyword.*;
	@SuppressWarnings({ "rawtypes", "unchecked", "unused" })

public class GamlAdditions extends AbstractGamlAdditions {
	public void initialize() throws SecurityException, NoSuchMethodException {
	initializeType();
	initializeVars();
	initializeOperator();
}public void initializeType()  {
_type("gen_population_generator",new genstar.gamaplugin.types.GamaPopGeneratorType(),938373948,104,genstar.gamaplugin.types.GamaPopGenerator.class);
_type("gen_range",new genstar.gamaplugin.types.GamaRangeType(),3524296,104,genstar.gamaplugin.types.GamaRange.class);
}public void initializeVars()  {
_field(genstar.gamaplugin.types.GamaRange.class,_proto("min_value",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaRange)v[0]).getMin(),2,genstar.gamaplugin.types.GamaRange.class,2,0,0));
_field(genstar.gamaplugin.types.GamaRange.class,_proto("max_value",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaRange)v[0]).getMax(),2,genstar.gamaplugin.types.GamaRange.class,2,0,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("attributes",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaPopGenerator)v[0]).getAttributeName(),5,genstar.gamaplugin.types.GamaPopGenerator.class,5,4,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("census_files",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaPopGenerator)v[0]).getCensusFile(),5,genstar.gamaplugin.types.GamaPopGenerator.class,5,4,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("generation_algo",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaPopGenerator)v[0]).getGenerationAlgorithm(),4,genstar.gamaplugin.types.GamaPopGenerator.class,4,0,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("mappers",null,10,genstar.gamaplugin.types.GamaPopGenerator.class,10,0,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("spatial_file",(s, v)->(v==null||v.length==0)? null:((genstar.gamaplugin.types.GamaPopGenerator)v[0]).getPathNestedGeometries(),4,genstar.gamaplugin.types.GamaPopGenerator.class,4,0,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("spatial_mapper_file",null,5,genstar.gamaplugin.types.GamaPopGenerator.class,5,4,0));
_field(genstar.gamaplugin.types.GamaPopGenerator.class,_proto("spatial_matcher_file",null,4,genstar.gamaplugin.types.GamaPopGenerator.class,4,0,0));
}public void initializeOperator() throws SecurityException, NoSuchMethodException {
_operator(S("add_attribute"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addAttribute",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,B,S,IType.class),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,B,S,IType.class),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addAttribute(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((IList)o[3]),asBool(s,o[4]),((String)o[5]),((IType)o[6])));
_operator(S("add_attribute"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addAttribute",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,S,IType.class),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,S,IType.class),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addAttribute(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((IList)o[3]),((String)o[4]),((IType)o[5])));
_operator(S("add_attribute"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addAttribute",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addAttribute(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((IList)o[3])));
_operator(S("add_attribute"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addAttribute",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,B),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,LI,B),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addAttribute(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((IList)o[3]),asBool(s,o[4])));
_operator(S("add_census_file"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addCensusFile",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S,S,i,i),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S,S,i,i),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addCensusFile(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2]),((String)o[3]),asInt(s,o[4]),asInt(s,o[5])));
_operator(S("add_mapper"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addMapper",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,GM,B),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,GM,B),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addMapper(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((GamaMap)o[3]),asBool(s,o[4])));
_operator(S("add_mapper"),genstar.gamaplugin.operators.GenstarAdderOperators.class.getMethod("addMapper",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,GM),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,IType.class,GM),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarAdderOperators.addMapper(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((IType)o[2]),((GamaMap)o[3])));
_operator(S("add_network"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("addGraphGenerator",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S,D),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S,D),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.addGraphGenerator(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2]),asFloat(s,o[3])));
_operator(S("add_network"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("addGraphGenerator",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S,I),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S,I),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.addGraphGenerator(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2]),asInt(s,o[3])));
_operator(S("get_network"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("get_graph",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,IGraph.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.get_graph(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
_operator(S("associate_population_agents"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("associatePopulation",SC,genstar.gamaplugin.types.GamaPopGenerator.class,GamlSpecies.class),C(genstar.gamaplugin.types.GamaPopGenerator.class,GamlSpecies.class),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.associatePopulation(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((GamlSpecies)o[1])));
_operator(S("add_network"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("addGraphGenerator",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S,D,I),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S,D,I),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.addGraphGenerator(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2]),asFloat(s,o[3]),asInt(s,o[4])));
_operator(S("add_network"),genstar.gamaplugin.operators.GenstarNetworkOperators.class.getMethod("addGraphGenerator",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarNetworkOperators.addGraphGenerator(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2])));
_operator(S("localize_around_at"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("localize_around_at",SC,genstar.gamaplugin.types.GamaPopGenerator.class,D,D),C(genstar.gamaplugin.types.GamaPopGenerator.class,D,D),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.localize_around_at(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),asFloat(s,o[1]),asFloat(s,o[2])));
_operator(S("localize_on_census"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("localize_on_census",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.localize_on_census(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
_operator(S("localize_around_at"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("localize_around_at",SC,genstar.gamaplugin.types.GamaPopGenerator.class,D,D,b),C(genstar.gamaplugin.types.GamaPopGenerator.class,D,D,b),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.localize_around_at(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),asFloat(s,o[1]),asFloat(s,o[2]),asBool(s,o[3])));
_operator(S("localize_on_geometries"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("localize_on_geometries",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.localize_on_geometries(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
_operator(S("add_spatial_distribution"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("addSpatialDistribution",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.addSpatialDistribution(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
_operator(S("add_spatial_mapper"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("addSpatialMapper",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.addSpatialMapper(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1]),((String)o[2])));
_operator(S("localize_around_at"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("localize_around_at",SC,genstar.gamaplugin.types.GamaPopGenerator.class,D),C(genstar.gamaplugin.types.GamaPopGenerator.class,D),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.localize_around_at(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),asFloat(s,o[1])));
_operator(S("add_ancilary_geofile"),genstar.gamaplugin.operators.GenstarLocalizeOperators.class.getMethod("addAncilaryGeoFiles",SC,genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarLocalizeOperators.addAncilaryGeoFiles(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
_operator(S("dummy_generator"),genstar.gamaplugin.operators.GenstarDefaultGenerationOperators.class.getMethod("dummyPopGeneration",SC,I),C(I),AI,LI,F,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarDefaultGenerationOperators.dummyPopGeneration(s,asInt(s,o[0])));
_operator(S("generate_entities"),genstar.gamaplugin.operators.GenstarGenerationOperators.class.getMethod("generateEntities",SC,genstar.gamaplugin.types.GamaPopGenerator.class),C(genstar.gamaplugin.types.GamaPopGenerator.class),AI,LI,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarGenerationOperators.generateEntities(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0])));
_operator(S("generate_localized_entities"),genstar.gamaplugin.operators.GenstarGenerationOperators.class.getMethod("generateLocalizedEntities",SC,genstar.gamaplugin.types.GamaPopGenerator.class,I),C(genstar.gamaplugin.types.GamaPopGenerator.class,I),AI,LI,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarGenerationOperators.generateLocalizedEntities(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),asInt(s,o[1])));
_operator(S("generate_entities"),genstar.gamaplugin.operators.GenstarGenerationOperators.class.getMethod("generateEntities",SC,genstar.gamaplugin.types.GamaPopGenerator.class,I),C(genstar.gamaplugin.types.GamaPopGenerator.class,I),AI,LI,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarGenerationOperators.generateEntities(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0]),asInt(s,o[1])));
_operator(S("generate_localized_entities"),genstar.gamaplugin.operators.GenstarGenerationOperators.class.getMethod("generateLocalizedEntities",SC,genstar.gamaplugin.types.GamaPopGenerator.class),C(genstar.gamaplugin.types.GamaPopGenerator.class),AI,LI,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarGenerationOperators.generateLocalizedEntities(s,((genstar.gamaplugin.types.GamaPopGenerator)o[0])));
_operator(S("with_generation_algo"),genstar.gamaplugin.operators.GenstarGenerationOperators.class.getMethod("withGenerationAlgo",genstar.gamaplugin.types.GamaPopGenerator.class,S),C(genstar.gamaplugin.types.GamaPopGenerator.class,S),AI,genstar.gamaplugin.types.GamaPopGenerator.class,T,-13,-13,-13,-13,(s,o)->genstar.gamaplugin.operators.GenstarGenerationOperators.withGenerationAlgo(((genstar.gamaplugin.types.GamaPopGenerator)o[0]),((String)o[1])));
}
}